name: Actions

on:
  pull_request:
    brances: ["*"]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run pytest
        run: docker-compose run --rm pytest
